<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-GJ3I4JJ" name="com.GladMinds.practice.Datatesting" tests="1" failures="0" timestamp="26 Mar 2018 04:24:02 GMT" time="0.802" errors="1">
  <testcase name="Test" time="0.802" classname="com.GladMinds.practice.Datatesting">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: Test([Parameter{index=0, type=java.util.HashMap, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {ROLLNO=999.0, LASTNAME=KJKJ, MIDNAME=MD, ADDRESS=US, FIRSTNAME=HHP},null,null,null,null]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: Data provider mismatchMethod: Test([Parameter{index=0, type=java.util.HashMap, declaredAnnotations=[]}])Arguments: [(java.util.HashMap) {ROLLNO=999.0, LASTNAME=KJKJ, MIDNAME=MD, ADDRESS=US, FIRSTNAME=HHP},null,null,null,null]at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)at org.testng.internal.Parameters.injectParameters(Parameters.java:796)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:973)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- Test -->
</testsuite> <!-- com.GladMinds.practice.Datatesting -->
